"""LSP stubs for Triton on macOS (no libtriton.so)."""

from typing import Any, Callable, Generic, Iterable, TypeVar, overload

from . import language as language
from . import testing as testing
from . import tools as tools

_T = TypeVar("_T", bound=Callable[..., Any])


class JITFunction(Generic[_T]):
    def __getitem__(self, grid: Any) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def run(self, *args: Any, **kwargs: Any) -> Any: ...


@overload
def jit(fn: _T) -> JITFunction[_T]: ...
@overload
def jit(
    *,
    version: Any = None,
    repr: Any = None,
    launch_metadata: Any = None,
    do_not_specialize: Iterable[int | str] | None = None,
    do_not_specialize_on_alignment: Iterable[int | str] | None = None,
    debug: bool | None = None,
    noinline: bool | None = None,
) -> Callable[[_T], JITFunction[_T]]: ...
def jit(*args: Any, **kwargs: Any) -> Any: ...

def cdiv(x: int, y: int) -> int: ...
def next_power_of_2(n: int) -> int: ...
def compile(*args: Any, **kwargs: Any) -> Any: ...
def autotune(*args: Any, **kwargs: Any) -> Any: ...
def heuristics(*args: Any, **kwargs: Any) -> Any: ...
def reinterpret(*args: Any, **kwargs: Any) -> Any: ...
def set_allocator(*args: Any, **kwargs: Any) -> None: ...

class Config: ...
class CompilationError(Exception): ...
class TritonError(Exception): ...
class OutOfResources(Exception): ...
class InterpreterError(Exception): ...
class TensorWrapper: ...
class MockTensor: ...
class KernelInterface: ...

must_use_result: Any
__version__: str
